version: '2'

services:
  postgresql:
    image: postgres:11.8-alpine
    environment:
      POSTGRES_PASSWORD: it_dev
      POSTGRES_USER: it_dev
      POSTGRES_DB: it_dev
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
      - '85:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: fiorenzino@gmail.com
      PGADMIN_DEFAULT_PASSWORD: flower
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data